import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import bcrypt from "bcryptjs";
import "dotenv/config";

const connectionString = process.env.DATABASE_URL;
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding Signal Regiment PIMS database...");

  // 1. Seed Admin User
  await prisma.user.deleteMany({});
  const hashedPassword = await bcrypt.hash("signal2026!", 10);

  await prisma.user.create({
    data: {
      username: "admin",
      email: "admin@signal.army.mil.ph",
      password: hashedPassword,
      name: "CPT Ramon V. Valderama",
      role: "ADMIN",
    },
  });
  console.log("Admin user seeded: admin / signal2026!");

  // 2. Seed Personnel Records
  await prisma.personnel.deleteMany({});

  const samplePersonnel = [
    {
      fullName: "Col. Mateo Delgado Cruz",
      serialNumber: "SR-2026-0001",
      rank: "Colonel",
      rankCategory: "Officer",
      birthday: new Date("1978-04-12"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 917 555 1001",
      email: "mateo.cruz@signal.army.mil.ph",
      address: "Fort Bonifacio, Taguig City, Metro Manila",
      unit: "Headquarters & Headquarters Company",
      position: "Regimental Chief of Staff",
      dateOfEnlistment: new Date("2000-06-15"),
      status: "Active",
    },
    {
      fullName: "LTC Arturo Gomez Santos",
      serialNumber: "SR-2026-0002",
      rank: "Lieutenant Colonel",
      rankCategory: "Officer",
      birthday: new Date("1982-08-20"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 918 555 1002",
      email: "arturo.santos@signal.army.mil.ph",
      address: "Camp Aquino, Tarlac City",
      unit: "1st Signal Battalion",
      position: "Battalion Commander",
      dateOfEnlistment: new Date("2004-04-10"),
      status: "Active",
    },
    {
      fullName: "MAJ Elena Rivera Navarro",
      serialNumber: "SR-2026-0003",
      rank: "Major",
      rankCategory: "Officer",
      birthday: new Date("1986-11-05"),
      gender: "Female",
      civilStatus: "Married",
      phone: "+63 920 555 1003",
      email: "elena.navarro@signal.army.mil.ph",
      address: "Camp Lapu-Lapu, Cebu City",
      unit: "2nd Signal Battalion",
      position: "Executive Officer",
      dateOfEnlistment: new Date("2008-05-18"),
      status: "Active",
    },
    {
      fullName: "CPT Ramon Valderama Bautista",
      serialNumber: "SR-2026-0004",
      rank: "Captain",
      rankCategory: "Officer",
      birthday: new Date("1990-01-14"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 922 555 1004",
      email: "ramon.bautista@signal.army.mil.ph",
      address: "Fort Magsaysay, Palayan City, Nueva Ecija",
      unit: "Signal Training School",
      position: "Chief Instructor / Operations Officer",
      dateOfEnlistment: new Date("2012-03-22"),
      status: "Active",
    },
    {
      fullName: "1LT Danica Reyes Mercado",
      serialNumber: "SR-2026-0005",
      rank: "First Lieutenant",
      rankCategory: "Officer",
      birthday: new Date("1993-07-29"),
      gender: "Female",
      civilStatus: "Single",
      phone: "+63 928 555 1005",
      email: "danica.mercado@signal.army.mil.ph",
      address: "Camp Evangelista, Cagayan de Oro City",
      unit: "3rd Signal Battalion",
      position: "Cyber Defense Team Lead",
      dateOfEnlistment: new Date("2015-09-01"),
      status: "Active",
    },
    {
      fullName: "2LT Gabriel Paolo Mendoza",
      serialNumber: "SR-2026-0006",
      rank: "Second Lieutenant",
      rankCategory: "Officer",
      birthday: new Date("1996-03-18"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 930 555 1006",
      email: "gabriel.mendoza@signal.army.mil.ph",
      address: "Fort Bonifacio, Taguig City",
      unit: "Signal Special Operations Battalion",
      position: "Tactical Communications Platoon Leader",
      dateOfEnlistment: new Date("2019-06-10"),
      status: "Active",
    },
    {
      fullName: "CMS Ferdinand Luna Soriano",
      serialNumber: "SR-2026-0007",
      rank: "Chief Master Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1975-09-10"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 917 555 2001",
      email: "ferdinand.soriano@signal.army.mil.ph",
      address: "Camp Aguinaldo, Quezon City",
      unit: "Headquarters & Headquarters Company",
      position: "Regimental Sergeant Major",
      dateOfEnlistment: new Date("1995-10-12"),
      status: "Active",
    },
    {
      fullName: "SMS Ricardo Dalisay Ramos",
      serialNumber: "SR-2026-0008",
      rank: "Senior Master Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1979-12-03"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 918 555 2002",
      email: "ricardo.ramos@signal.army.mil.ph",
      address: "Camp Aquino, Tarlac City",
      unit: "1st Signal Battalion",
      position: "Battalion Chief Communications NCO",
      dateOfEnlistment: new Date("1999-04-15"),
      status: "Active",
    },
    {
      fullName: "MSG Hernando Garcia Villanueva",
      serialNumber: "SR-2026-0009",
      rank: "Master Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1981-05-24"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 920 555 2003",
      email: "hernando.villanueva@signal.army.mil.ph",
      address: "Camp Lapu-Lapu, Cebu City",
      unit: "2nd Signal Battalion",
      position: "Satellite Communications Specialist",
      dateOfEnlistment: new Date("2002-08-01"),
      status: "Active",
    },
    {
      fullName: "TSG Maricel Aquino Torres",
      serialNumber: "SR-2026-0010",
      rank: "Technical Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1985-02-17"),
      gender: "Female",
      civilStatus: "Married",
      phone: "+63 922 555 2004",
      email: "maricel.torres@signal.army.mil.ph",
      address: "Fort Magsaysay, Palayan City",
      unit: "Signal Training School",
      position: "Senior Radio Operations Instructor",
      dateOfEnlistment: new Date("2006-11-20"),
      status: "Active",
    },
    {
      fullName: "SSG Kenneth Joel Castro",
      serialNumber: "SR-2026-0011",
      rank: "Staff Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1989-10-30"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 928 555 2005",
      email: "kenneth.castro@signal.army.mil.ph",
      address: "Camp Evangelista, Cagayan de Oro City",
      unit: "3rd Signal Battalion",
      position: "Network Infrastructure Specialist",
      dateOfEnlistment: new Date("2010-02-14"),
      status: "Active",
    },
    {
      fullName: "SGT Jasmine Faith Morales",
      serialNumber: "SR-2026-0012",
      rank: "Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1992-06-15"),
      gender: "Female",
      civilStatus: "Single",
      phone: "+63 930 555 2006",
      email: "jasmine.morales@signal.army.mil.ph",
      address: "Fort Bonifacio, Taguig City",
      unit: "Signal Special Operations Battalion",
      position: "Electronic Warfare Systems Operator",
      dateOfEnlistment: new Date("2014-07-07"),
      status: "Active",
    },
    {
      fullName: "CPL Vincent Paul Salazar",
      serialNumber: "SR-2026-0013",
      rank: "Corporal",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1995-04-08"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 932 555 2007",
      email: "vincent.salazar@signal.army.mil.ph",
      address: "Camp Aquino, Tarlac City",
      unit: "1st Signal Battalion",
      position: "Microwave Relay Station Technician",
      dateOfEnlistment: new Date("2017-01-19"),
      status: "Active",
    },
    {
      fullName: "PFC Angelo Miguel Fernandez",
      serialNumber: "SR-2026-0014",
      rank: "Private First Class",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1998-09-22"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 935 555 2008",
      email: "angelo.fernandez@signal.army.mil.ph",
      address: "Camp Lapu-Lapu, Cebu City",
      unit: "2nd Signal Battalion",
      position: "Field Radio Operator",
      dateOfEnlistment: new Date("2020-03-10"),
      status: "Active",
    },
    {
      fullName: "PVT Kristine Joy Alcantara",
      serialNumber: "SR-2026-0015",
      rank: "Private",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("2001-12-05"),
      gender: "Female",
      civilStatus: "Single",
      phone: "+63 938 555 2009",
      email: "kristine.alcantara@signal.army.mil.ph",
      address: "Fort Magsaysay, Palayan City",
      unit: "Signal Training School",
      position: "Signal Apprentice",
      dateOfEnlistment: new Date("2023-08-15"),
      status: "Active",
    },
    {
      fullName: "BGEN Rolando Perez Tan",
      serialNumber: "SR-2026-0016",
      rank: "Brigadier General",
      rankCategory: "Officer",
      birthday: new Date("1965-01-30"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 917 555 3001",
      email: "rolando.tan@retired.army.mil.ph",
      address: "Quezon City, Metro Manila",
      unit: "Headquarters & Headquarters Company",
      position: "Former Regiment Commander",
      dateOfEnlistment: new Date("1987-03-01"),
      status: "Retired",
    },
    {
      fullName: "MSG Bonifacio Santos Tolentino",
      serialNumber: "SR-2026-0017",
      rank: "Master Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1968-08-14"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 918 555 3002",
      email: "bonifacio.tolentino@retired.army.mil.ph",
      address: "San Fernando, Pampanga",
      unit: "1st Signal Battalion",
      position: "Former Senior Radio Technician",
      dateOfEnlistment: new Date("1989-07-20"),
      status: "Retired",
    },
    {
      fullName: "CPT Leila Camille Domingo",
      serialNumber: "SR-2026-0018",
      rank: "Captain",
      rankCategory: "Officer",
      birthday: new Date("1988-11-19"),
      gender: "Female",
      civilStatus: "Married",
      phone: "+63 920 555 4001",
      email: "leila.domingo@res.army.mil.ph",
      address: "Pasig City, Metro Manila",
      unit: "Signal Special Operations Battalion",
      position: "Reserve Communications Systems Consultant",
      dateOfEnlistment: new Date("2016-05-12"),
      status: "Reserve",
    },
    {
      fullName: "TSG Rodolfo Esguerra Pineda",
      serialNumber: "SR-2026-0019",
      rank: "Technical Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1987-03-25"),
      gender: "Male",
      civilStatus: "Married",
      phone: "+63 922 555 4002",
      email: "rodolfo.pineda@res.army.mil.ph",
      address: "Davao City, Davao del Sur",
      unit: "3rd Signal Battalion",
      position: "Reserve IT Network Specialist",
      dateOfEnlistment: new Date("2013-10-08"),
      status: "Reserve",
    },
    {
      fullName: "1LT Mark Anthony David",
      serialNumber: "SR-2026-0020",
      rank: "First Lieutenant",
      rankCategory: "Officer",
      birthday: new Date("1994-08-11"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 927 555 1010",
      email: "mark.david@signal.army.mil.ph",
      address: "Camp Aquino, Tarlac City",
      unit: "1st Signal Battalion",
      position: "Battalion Signal Officer (S6)",
      dateOfEnlistment: new Date("2017-04-18"),
      status: "Active",
    },
    {
      fullName: "SGT Patricia Anne Corpuz",
      serialNumber: "SR-2026-0021",
      rank: "Sergeant",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1993-01-28"),
      gender: "Female",
      civilStatus: "Single",
      phone: "+63 929 555 2011",
      email: "patricia.corpuz@signal.army.mil.ph",
      address: "Camp Lapu-Lapu, Cebu City",
      unit: "2nd Signal Battalion",
      position: "Crypto Communications Specialist",
      dateOfEnlistment: new Date("2015-11-03"),
      status: "Active",
    },
    {
      fullName: "CPL Joshua Ethan Lim",
      serialNumber: "SR-2026-0022",
      rank: "Corporal",
      rankCategory: "Enlisted Personnel",
      birthday: new Date("1996-10-15"),
      gender: "Male",
      civilStatus: "Single",
      phone: "+63 931 555 2012",
      email: "joshua.lim@signal.army.mil.ph",
      address: "Fort Magsaysay, Palayan City",
      unit: "Signal Training School",
      position: "Radar Maintenance Technician",
      dateOfEnlistment: new Date("2018-09-24"),
      status: "Active",
    },
  ];

  for (const person of samplePersonnel) {
    await prisma.personnel.create({
      data: person,
    });
  }

  console.log(`Seeded ${samplePersonnel.length} personnel records successfully with Serial Numbers.`);
}

main()
  .catch((e) => {
    console.error("Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
