<?php

namespace Database\Seeders;

use App\Models\Personnel;
use Illuminate\Database\Seeder;

class PersonnelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'serial_number' => 'SIG-2018-001',
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'rank' => 'SGT',
                'birthday' => '1992-03-15',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09171234567',
                'email' => 'jdelacruz@signal.mil',
                'address' => 'Fort Bonifacio, Taguig City',
                'unit' => 'Signal Company Alpha',
                'position' => 'Communications NCO',
                'date_of_enlistment' => '2018-06-01',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2019-002',
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'rank' => 'CPL',
                'birthday' => '1995-07-22',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09182345678',
                'email' => 'msantos@signal.mil',
                'address' => 'Camp Aguinaldo, Quezon City',
                'unit' => 'Signal Battalion HQ',
                'position' => 'Radio Operator',
                'date_of_enlistment' => '2019-01-15',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2017-003',
                'first_name' => 'Ricardo',
                'last_name' => 'Reyes',
                'rank' => 'SSG',
                'birthday' => '1988-11-05',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09193456789',
                'email' => 'rreyes@signal.mil',
                'address' => 'Camp Crame, Quezon City',
                'unit' => 'Signal Company Bravo',
                'position' => 'Platoon Sergeant',
                'date_of_enlistment' => '2017-03-10',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2020-004',
                'first_name' => 'Ana',
                'last_name' => 'Gonzales',
                'rank' => '1LT',
                'birthday' => '1993-09-18',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09204567890',
                'email' => 'agonzales@signal.mil',
                'address' => 'Villamor Air Base, Pasay City',
                'unit' => 'Cyber Defense Squadron',
                'position' => 'Cyber Security Officer',
                'date_of_enlistment' => '2020-02-01',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2015-005',
                'first_name' => 'Eduardo',
                'last_name' => 'Mendoza',
                'rank' => 'CPT',
                'birthday' => '1986-04-12',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09215678901',
                'email' => 'emendoza@signal.mil',
                'address' => 'Camp General Emilio Aguinaldo, QC',
                'unit' => '1st Signal Brigade',
                'position' => 'Company Commander',
                'date_of_enlistment' => '2015-08-20',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2021-006',
                'first_name' => 'Cristina',
                'last_name' => 'Aquino',
                'rank' => 'PFC',
                'birthday' => '1998-12-30',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09226789012',
                'email' => 'caquino@signal.mil',
                'address' => 'Fort Magsaysay, Nueva Ecija',
                'unit' => 'Signal Company Charlie',
                'position' => 'Field Communications Specialist',
                'date_of_enlistment' => '2021-05-11',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2016-007',
                'first_name' => 'Mark',
                'last_name' => 'Bautista',
                'rank' => 'SFC',
                'birthday' => '1985-02-14',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09237890123',
                'email' => 'mbautista@signal.mil',
                'address' => 'Camp Aquino, Tarlac City',
                'unit' => 'Electronic Warfare Battalion',
                'position' => 'EW Senior Technician',
                'date_of_enlistment' => '2016-10-04',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2022-008',
                'first_name' => 'Patricia',
                'last_name' => 'Villanueva',
                'rank' => 'PVT',
                'birthday' => '2001-08-25',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09248901234',
                'email' => 'pvillanueva@signal.mil',
                'address' => 'Camp Servillano Aquino, Tarlac',
                'unit' => 'Signal Company Alpha',
                'position' => 'Junior Radio Operator',
                'date_of_enlistment' => '2022-04-18',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2012-009',
                'first_name' => 'Antonio',
                'last_name' => 'Fernandez',
                'rank' => 'MAJ',
                'birthday' => '1980-01-20',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09259012345',
                'email' => 'afernandez@signal.mil',
                'address' => 'Camp Lapu-Lapu, Cebu City',
                'unit' => 'Signal Battalion HQ',
                'position' => 'Operations Officer (G3)',
                'date_of_enlistment' => '2012-03-01',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2014-010',
                'first_name' => 'Lourdes',
                'last_name' => 'Castillo',
                'rank' => 'MSG',
                'birthday' => '1982-06-14',
                'gender' => 'Female',
                'civil_status' => 'Widowed',
                'phone' => '09260123456',
                'email' => 'lcastillo@signal.mil',
                'address' => 'Camp Evangelista, Cagayan de Oro',
                'unit' => 'Satellite Communications Unit',
                'position' => 'SATCOM Station Chief',
                'date_of_enlistment' => '2014-07-15',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2019-011',
                'first_name' => 'Ramon',
                'last_name' => 'Pascual',
                'rank' => 'SGT',
                'birthday' => '1991-10-09',
                'gender' => 'Male',
                'civil_status' => 'Separated',
                'phone' => '09271234560',
                'email' => 'rpascual@signal.mil',
                'address' => 'Fort Del Pilar, Baguio City',
                'unit' => 'Signal Company Bravo',
                'position' => 'Signal Line Specialist',
                'date_of_enlistment' => '2019-09-01',
                'status' => 'Reserve',
            ],
            [
                'serial_number' => 'SIG-2023-012',
                'first_name' => 'Stephanie',
                'last_name' => 'Navarro',
                'rank' => '2LT',
                'birthday' => '1997-05-03',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09282345671',
                'email' => 'snavarro@signal.mil',
                'address' => 'Camp Panacan, Davao City',
                'unit' => 'Cyber Defense Squadron',
                'position' => 'Information Warfare Analyst',
                'date_of_enlistment' => '2023-01-10',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2010-013',
                'first_name' => 'Rodrigo',
                'last_name' => 'Mercado',
                'rank' => 'LTC',
                'birthday' => '1976-12-01',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09293456782',
                'email' => 'rmercado@signal.mil',
                'address' => 'Camp Capinpin, Tanay, Rizal',
                'unit' => '1st Signal Brigade',
                'position' => 'Battalion Commander',
                'date_of_enlistment' => '2010-04-12',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2013-014',
                'first_name' => 'Grace',
                'last_name' => 'Tolentino',
                'rank' => 'SGM',
                'birthday' => '1979-08-19',
                'gender' => 'Female',
                'civil_status' => 'Married',
                'phone' => '09304567893',
                'email' => 'gtolentino@signal.mil',
                'address' => 'Fort Andres Bonifacio, Metro Manila',
                'unit' => 'Signal Battalion HQ',
                'position' => 'Regimental Sergeant Major',
                'date_of_enlistment' => '2013-11-20',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2020-015',
                'first_name' => 'Ferdinand',
                'last_name' => 'Ramos',
                'rank' => 'CPL',
                'birthday' => '1994-03-27',
                'gender' => 'Male',
                'civil_status' => 'Single',
                'phone' => '09315678904',
                'email' => 'framos@signal.mil',
                'address' => 'Camp Navarro, Zamboanga City',
                'unit' => 'Signal Company Charlie',
                'position' => 'Tactical Radio Operator',
                'date_of_enlistment' => '2020-08-15',
                'status' => 'AWOL',
            ],
            [
                'serial_number' => 'SIG-2011-016',
                'first_name' => 'Danilo',
                'last_name' => 'Ocampo',
                'rank' => 'COL',
                'birthday' => '1972-04-05',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09326789015',
                'email' => 'docampo@signal.mil',
                'address' => 'GHQ Camp Aguinaldo, Quezon City',
                'unit' => '1st Signal Brigade',
                'position' => 'Brigade Commander',
                'date_of_enlistment' => '2011-01-05',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2010-017',
                'first_name' => 'Vicente',
                'last_name' => 'Soriano',
                'rank' => 'SFC',
                'birthday' => '1968-09-14',
                'gender' => 'Male',
                'civil_status' => 'Married',
                'phone' => '09337890126',
                'email' => 'vsoriano@signal.mil',
                'address' => 'Camp Melchor Dela Cruz, Gamu, Isabela',
                'unit' => 'Signal Company Alpha',
                'position' => 'Senior Comms Advisor',
                'date_of_enlistment' => '2010-02-15',
                'status' => 'Retired',
            ],
            [
                'serial_number' => 'SIG-2018-018',
                'first_name' => 'Jocelyn',
                'last_name' => 'Valdez',
                'rank' => 'SSG',
                'birthday' => '1990-11-23',
                'gender' => 'Female',
                'civil_status' => 'Divorced',
                'phone' => '09348901237',
                'email' => 'jvaldez@signal.mil',
                'address' => 'Camp Macario Sakay, Los Baños, Laguna',
                'unit' => 'Electronic Warfare Battalion',
                'position' => 'Signals Intelligence Specialist',
                'date_of_enlistment' => '2018-07-22',
                'status' => 'Reserve',
            ],
            [
                'serial_number' => 'SIG-2022-019',
                'first_name' => 'Gabriel',
                'last_name' => 'Alcantara',
                'rank' => 'PFC',
                'birthday' => '1999-02-17',
                'gender' => 'Male',
                'civil_status' => 'Single',
                'phone' => '09359012348',
                'email' => 'galcantara@signal.mil',
                'address' => 'Camp Artemio Ricarte, Puerto Princesa',
                'unit' => 'Satellite Communications Unit',
                'position' => 'Antenna & Satellite Rigging Specialist',
                'date_of_enlistment' => '2022-09-01',
                'status' => 'Active',
            ],
            [
                'serial_number' => 'SIG-2024-020',
                'first_name' => 'Rowena',
                'last_name' => 'Cruz',
                'rank' => 'PVT',
                'birthday' => '2002-10-11',
                'gender' => 'Female',
                'civil_status' => 'Single',
                'phone' => '09360123459',
                'email' => 'rcruz@signal.mil',
                'address' => 'Fort Ramon Magsaysay, Palayan City',
                'unit' => 'Signal Company Bravo',
                'position' => 'Field Wireman',
                'date_of_enlistment' => '2024-03-01',
                'status' => 'Active',
            ],
        ];

        foreach ($records as $record) {
            Personnel::updateOrCreate(
                ['serial_number' => $record['serial_number']],
                $record
            );
        }
    }
}
